name: Production Continous Integration (CI)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_build:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Temporary .env.prod
        run: |
          touch .env.prod
          echo ${{ secrets.ENV_PROD_FILE }} >> .env.prod

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile 
        
      - name: Lint All Projects
        run: yarn nx run-many --target=lint

      - name: Run Tests and Create Coverage Report
        run: yarn test:ci

      - name: Upload Coverage Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Application
        run: yarn build:app:prod

      - name: Build API
        run: yarn build:api:prod

      - name: Build CLI
        run: yarn build:cli:prod