name: Development | Deploy to Firebase
'on':
  workflow_run:
    workflows: ["ðŸ³ NRWL NX"]
    types:
      - completed
  push:
    branches:
      - dev
jobs:
  build:
    name: "Building App"
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ›ï¸ Checkout repository
        uses: actions/checkout@v3
        
      - name: ðŸ“ Create ENV File
        run: |
          touch .env
          echo NX_ENVIRONMENT="development" >> .env
          echo NX_FIREBASE_AUTH_DOMAIN='${{secrets.NX_FIREBASE_AUTH_DOMAIN}}' >> .env
          echo NX_FIREBASE_DATABASE_URL='${{ secrets.NX_FIREBASE_DATABASE_URL }}' >> .env
          echo NX_FIREBASE_PROJECT_ID='${{secrets.NX_FIREBASE_PROJECT_ID}}' >> .env
          echo NX_FIREBASE_STORAGE_BUCKET='${{secrets.NX_FIREABASE_STORAGE_BUCKET}}' >> .env
          echo NX_FIREBASE_MESSAGING_SENDER_ID='${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}' >> .env
          echo NX_FIREBASE_APP_ID='${{ secrets.NX_FIREBASE_APP_ID }}' >> .env
          echo NX_FIREBASE_MEASUREMENT_ID='${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}' >> .env
          echo NX_FIREBASE_API_KEY='${{ secrets.NX_FIREBASE_API_KEY }}' >> .env
          # cat .env
        
      - name: ðŸ§° Installing packages and buidling app
        run: yarn install --frozen-lockfile && yarn build:app:dev && yarn build:api:dev
        
      - name: ðŸ”¥ Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT_DEV }}'
          projectId: '${{ secrets.NX_FIREBASE_PROJECT_ID }}'
          channelId: live
          
      - name: ðŸ”¥ Deploy to Firebase Cloud Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project development
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT_DEV }}
          PROJECT_ID: '${{ secrets.NX_FIREBASE_PROJECT_ID }}'
