name: ğŸ³ NRWL NX
on: push

jobs:
  nrwl_test:
    name: "ğŸ³ NRWL NX Text"
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout repository
        uses: actions/checkout@v3
    
      - uses: mskelton/setup-yarn@v1
        
      - name: ğŸ‹ NX Lint
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint
          
      - name: ğŸ‹ NX Test
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: test
          all: true
          parallel: 5
          args: --skip-nx-cache --configuration=ci
