name: "Main: Firebase Deploy on Merge"
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: "ðŸ”¥ Deploy to Firebase Production"
    environment: firebase
    runs-on: ubuntu-latest
    steps:
      - name: "â¤ï¸ Checking out Repo"
        uses: actions/checkout@v2
      - name: "ðŸ“š Create ENV"
        run: |
          touch .env.prod
          echo NX_ENVIRONMENT="production" >> .env.prod
          echo NX_FIREBASE_AUTH_DOMAIN='${{secrets.NX_FIREBASE_AUTH_DOMAIN}}' >> .env.prod
          echo NX_FIREBASE_DATABASE_URL='${{ secrets.NX_FIREBASE_DATABASE_URL }}' >> .env.prod
          echo NX_FIREBASE_PROJECT_ID='${{secrets.NX_FIREBASE_PROJECT_ID}}' >> .env.prod
          echo NX_FIREBASE_STORAGE_BUCKET='${{secrets.NX_FIREABASE_STORAGE_BUCKET}}' >> .env.prod
          echo NX_FIREBASE_MESSAGING_SENDER_ID='${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}' >> .env.prod
          echo NX_FIREBASE_APP_ID='${{ secrets.NX_FIREBASE_APP_ID }}' >> .env.prod
          echo NX_FIREBASE_MEASUREMENT_ID='${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}' >> .env.prod
          echo NX_FIREBASE_API_KEY='${{ secrets.NX_FIREBASE_API_KEY }}' >> .env.prod
          cat .env.prod
      - name: "ðŸ“š Create firebasesc"
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".firebasesc"
          FILE_DATA: "${{secrets.FIREBASESC}}"
      - name: "ðŸ‘· Installing Packages on Worker"
        run: yarn install --frozen-lockfile && yarn build:app:prod
      - name: "ðŸ”¨ Deploying to Firebase"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COS301_MINIPROJECT }}'
          channelId: live
          projectId: '${{secrets.NX_FIREBASE_PROJECT_ID}}'