name: Tests
'on':
  push:
    branches:
      - '*'
jobs:
  build_and_deploy:
    name: "ğŸ”¥ Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "â¤ï¸ Checking out Repo"
        uses: actions/checkout@v2
      - name: "ğŸ“š Run Tests"
        run: "nx run-many --target=test --all --skip-nx-cache --parallel=5 --configuration=ci"
